export const Data = [
  {
    id: "1",
    fname: "John",
    lname: "Doe",
    email: "johndoe@example.com",
  },
  {
    id: "2",
    fname: "Jane",
    lname: "Doe",
    email: "janedoe@example.com",
  },
  {
    id: "3",
    fname: "Bob",
    lname: "Smith",
    email: "bobsmith@example.com",
  },
  {
    id: "4",
    fname: "Alice",
    lname: "Jones",
    email: "alicejones@example.com",
  },
  {
    id: "5",
    fname: "Mark",
    lname: "Johnson",
    email: "markjohnson@example.com",
  },
  {
    id: "6",
    fname: "Sarah",
    lname: "Williams",
    email: "sarahwilliams@example.com",
  },
  {
    id: "7",
    fname: "Mike",
    lname: "Brown",
    email: "mikebrown@example.com",
  },
  {
    id: "8",
    fname: "Emily",
    lname: "Davis",
    email: "emilydavis@example.com",
  },
  {
    id: "9",
    fname: "David",
    lname: "Garcia",
    email: "davidgarcia@example.com",
  },
  {
    id: "10",
    fname: "Karen",
    lname: "Rodriguez",
    email: "karenrodriguez@example.com",
  },
  {
    id: "11",
    fname: "Jason",
    lname: "Martinez",
    email: "jasonmartinez@example.com",
  },
  {
    id: "12",
    fname: "Rachel",
    lname: "Lee",
    email: "rachellee@example.com",
  },
  {
    id: "13",
    fname: "Kevin",
    lname: "Gonzalez",
    email: "kevingonzalez@example.com",
  },
  {
    id: "14",
    fname: "Linda",
    lname: "Perez",
    email: "lindaperez@example.com",
  },
  {
    id: "15",
    fname: "Andrew",
    lname: "Taylor",
    email: "andrewtaylor@example.com",
  },
  {
    id: "16",
    fname: "Jessica",
    lname: "Anderson",
    email: "jessicaanderson@example.com",
  },
  {
    id: "17",
    fname: "Brian",
    lname: "Jackson",
    email: "brianjackson@example.com",
  },
  {
    id: "18",
    fname: "Samantha",
    lname: "White",
    email: "samanthawhite@example.com",
  },
  {
    id: "19",
    fname: "Chris",
    lname: "Davis",
    email: "chrisdavis@example.com",
  },
  {
    id: "20",
    fname: "Ashley",
    lname: "Morris",
    email: "ashleymorris@example.com",
  },
];
